name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install generate
      run: cargo install cargo-generate
    - name: create demo object
      run: cargo generate ${{ github.repository }}@${{ github.sha }} -n testgame -d window-title=default
    - name: Build
      run: cargo build --verbose
      working-directory: testgame
    - name: Run tests
      run: cargo test --verbose
      working-directory: testgame
